# Generated by Django 5.1.7 on 2026-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0006_textbook_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbook",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="textbook",
            name="school_class",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="textbook",
            name="subject",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="textbook",
            index=models.Index(fields=["price"], name="marketplace_price_7c20cf_idx"),
        ),
        migrations.AddIndex(
            model_name="textbook",
            index=models.Index(
                fields=["condition"], name="marketplace_conditi_357fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textbook",
            index=models.Index(
                fields=["-created_at"], name="marketplace_created_dabe9d_idx"
            ),
        ),
    ]
