# Generated by Django 5.1.7 on 2025-05-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
