# Generated by Django 5.1.7 on 2025-05-15 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_message_seen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=models.SET(None),
                related_name="message_recipient",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=models.SET(None),
                related_name="message_sender",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
